/*
 * GOV.UK Pay API
 * GOV.UK Pay API
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.gov.pay.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.gov.pay.api.model.CardPayment;

/**
* PaymentSearchResults
*/
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-04T16:15:55.686+01:00")
public class PaymentSearchResults   {
        @JsonProperty("results")
        private List<CardPayment> results = null;


        public PaymentSearchResults results(List<CardPayment> results) {
        this.results = results;
        return this;
        }

            public PaymentSearchResults addResultsItem(CardPayment resultsItem) {
                if (this.results == null) {
                this.results = new ArrayList<CardPayment>();
                }
            this.results.add(resultsItem);
            return this;
            }

    /**
        * Get results
    * @return results
    **/
        @JsonProperty("results")
    @ApiModelProperty(value = "")
      public List<CardPayment> getResults() {
    return results;
    }

        public void setResults(List<CardPayment> results) {
        this.results = results;
        }


    @Override
    public boolean equals(java.lang.Object o) {
    if (this == o) {
    return true;
    }
    if (o == null || getClass() != o.getClass()) {
    return false;
    }
        PaymentSearchResults paymentSearchResults = (PaymentSearchResults) o;
        return Objects.equals(this.results, paymentSearchResults.results);
    }

    @Override
    public int hashCode() {
    return Objects.hash(results);
    }


@Override
public String toString() {
StringBuilder sb = new StringBuilder();
sb.append("class PaymentSearchResults {\n");

sb.append("    results: ").append(toIndentedString(results)).append("\n");
sb.append("}");
return sb.toString();
}

/**
* Convert the given object to string with each line indented by 4 spaces
* (except the first line).
*/
private String toIndentedString(java.lang.Object o) {
if (o == null) {
return "null";
}
return o.toString().replace("\n", "\n    ");
}
}
