package uk.gov.pay.api.app;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.dropwizard.Application;
import io.dropwizard.auth.AuthFactory;
import io.dropwizard.auth.oauth.OAuthFactory;
import io.dropwizard.configuration.EnvironmentVariableSubstitutor;
import io.dropwizard.configuration.SubstitutingSourceProvider;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import io.swagger.jaxrs.config.BeanConfig;
import io.swagger.jaxrs.listing.ApiListingResource;
import uk.gov.pay.api.auth.AccountAuthenticator;
import uk.gov.pay.api.config.PublicApiConfig;
import uk.gov.pay.api.healthcheck.Ping;
import uk.gov.pay.api.resources.PaymentsResource;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;

public class PublicApi extends Application<PublicApiConfig> {

    @Override
    public void initialize(Bootstrap<PublicApiConfig> bootstrap) {
        bootstrap.setConfigurationSourceProvider(
                new SubstitutingSourceProvider(
                        bootstrap.getConfigurationSourceProvider(),
                        new EnvironmentVariableSubstitutor(false)
                )
        );
    }

    @Override
    public void run(PublicApiConfig config, Environment environment) throws Exception {
        final Client client = ClientBuilder.newBuilder().build();

        environment.healthChecks().register("ping", new Ping());
        environment.jersey().register(new PaymentsResource(client, config.getConnectorUrl()));
        environment.jersey().register(AuthFactory.binder(new OAuthFactory<>(new AccountAuthenticator(client, config.getPublicAuthUrl()),
                "",
                String.class)));

        //The line below is needed to exclude 'null' properties from the JSON generated by Swagger.
        //A JSON document with 'null' properties cannot be parsed by Gelato
        environment.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
        environment.jersey().register(new ApiListingResource());
        BeanConfig swaggerConfig = new BeanConfig();
        swaggerConfig.setTitle("GDS Payments Api");
        swaggerConfig.setVersion("1.0.0");
        swaggerConfig.setResourcePackage("uk.gov.pay.api.resources");
        swaggerConfig.setScan(true);
    }

    public static void main(String[] args) throws Exception {
        new PublicApi().run(args);
    }
}
